 <!DOCTYPE html>
<html lang="en">
<?php
    $pageID = "about";
    include("../incl/head.php");
?>
<body>

<?php include("../incl/nav.php"); ?>

    <div id="pageHeader" class="jumbotron jumbotron-fluid container-fluid text-center" style="padding-right: 15px; padding-left: 15px;">
        <div class="row">
            <div class="col-12 h3">About Us</div>
        </div>
    </div>
    
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="float-left" style="width: 40%; margin-right: 4%; margin-bottom: 2%;">
                    <img class="rounded" style="width: 100%" src="../images/statesboro.jpg">
                </div>
                During August of 2020, the laws preventing the sale of liquor within Stateboro were finally lifted. Dr.
                Jim Harris of Georgia Southern University saw this as a chance to retire from his career as a professor
                and realize his vision of creating a liquor store with both a wide selection of products and the
                lowest prices available to help Georgia Southern students cope with the stresses of school life.
                <br><br>
                During his time as a professor, Dr. Harris witnessed first-hand the detrimental effects of the harsh
                liquor laws imposed on himself and his students. Attendance reached an all-time low as students were
                forced to work multiple jobs to be able to afford to drink at the local bars in Statesboro. It was then
                that Dr. Harris vowed that if the tyrannical laws were ever lifted, he would establish a convenient,
                fairly priced liquor store that offered a discount to college students.
                <br><br>
                Due to his background in the field of computer science, Dr. Harris is very well acquainted with modern
                digital security techniques and practices. He used this knowledge to implement state of the art security
                within Harris Package from the moment its doors were opened. A prime example of this is HarrisWatch, a
                network of 37 different cameras located throughout the facility linked to a machine running Dr. Harris's
                patented HarrisWatch software. His software uses modern machine learning techniques to identify
                attempted shoplifting with 99.998% accuracy. It has proved to be extremely successful, with its first
                suspected shoplifter being arrested before he was able to even make it to his vehicle.
                <br><br>
                Customers can also rest easy knowing that their information is safe within the store's database. During
                the last attempted network breach, three former students who attempted the attack had their hard drives
                encrypted, rendering them completely useless without the key generated by Dr. Harris's CounterAttack
                software. The suspects were arrested when they came to Harris for the key. This attack was a fruitless
                endeavor to begin with as all of the stored customer information is encrypted anyway.
                <br><br>
                Since Harris Package opened, it has quickly become the hottest liquor store in town. Be sure to stay up
                to date with the latest deals on our website to get the most bang for your buck. Come in and see why
                Georgia Southern students rank Harris Package as the #1 liquor store in Statesboro!
            </div>
        </div>
    </div>
    
<?php include("../incl/footer.php"); ?>

</body>
</html>